### ISSUE TITLE
Segmentation fault after ascending, after showing the conducts

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#19] opened 2015-06-20 16:25 UTC
What the title says. After ascending, it sais all the stuff you did.
After displaying  the conducts, segmentation fault....

**Comment by Soviet5lo** [comment] 2020-02-04 05:10
Ever since doing a flood of commits mid-2019 I haven't been able to reproduce this, at least in wizard mode testing.  Closing this for now.

**Closed by Soviet5lo** 2020-02-04 05:10 UTC
