### ISSUE TITLE
segmentation fault and "  [neutral strange object]" with artifacts in discoveries

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#7] opened 2015-06-09 20:10 UTC
Here's my list of artifacts in discoveries. "neutral strange object" is supposed to be the crown of saint edward. Well i think it's that, no other possibility. When i try premium identify on it in a shop it tells me it's alredy identified. Note, that there is just a space in place of the name, it's not just empty.

I haven't got the tsurugy of muramasa and the bell but i did reach the level with the nemesis

I can send you my save file if you want

 Artifacts
   Kiku-ichimonji [lawful katana]
   Excalibur [lawful chokuto]
   Hellfire [chaotic crossbow]
   Icebiter [lawful axe]
   Scales of the Dragon Lord [chaotic gray dragon scale mail]
   Nighthorn [lawful unicorn horn]
   The Key of Law [lawful skeleton key]
   Wallet of Perseus [unaligned bag of holding]
    [neutral strange object]
   The Key of Neutrality [neutral skeleton key]
   The Hand of Vecna [chaotic severed hand]
   The Eye of the Beholder [neutral eyeball]
   The Key of Chaos [chaotic skeleton key]

**Comment by Soviet5lo** [comment] 2015-06-12 02:03
This seems to also be a Slash'EM Extended issue.  I'm...not exactly sure what would cause such an issue, but I'll report it to the slex developer, and backport it's fix for the next release.

**Comment by pirate486743186** [comment] 2015-06-12 04:22
upgrade this to fatal!
as a samurai i tried various artifacts:

"Mantle of Heaven" and "the tsurugi of muramasa"
gave segmentation faults. The tsurugi too :'(
good thing i didn't bother with the quest yet.
i think it will be easier to find the problem now.

For these bellow, no problem

Doomblade [chaotic orcish short sword]
Bat from Hell [chaotic jo]
Magicbane [neutral athame]
The Magic Mirror of Merlin [lawful mirror]
Kiku-ichimonji [lawful katana]
Excalibur [lawful chokuto]
Hellfire [chaotic crossbow]
Icebiter [lawful axe]
Scales of the Dragon Lord [chaotic gray dragon scale mail]
Nighthorn [lawful unicorn horn]
The Key of Law [lawful skeleton key]
Wallet of Perseus [unaligned bag of holding]
The Key of Neutrality [neutral skeleton key]
The Hand of Vecna [chaotic severed hand]
The Eye of the Beholder [neutral eyeball]
The Key of Chaos [chaotic skeleton key]

**Comment by Soviet5lo** [comment] 2015-06-13 02:53
Apparently the issue is any artifact that has a value above 127 will crash the discovery screen, which is mostly quest artifacts.  I'm...not exactly sure why this is happening however, since artifacts are stored as int and not char anymore.  This definitely also exists in Slash'EM Extended, and the developer of that variant also has no idea why this continues to occur.

**Comment by AmyBSOD** [comment] 2015-06-17 05:58
For a temporary fix, see this: https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/89fe13fa2061d457fdbdfaefe0d1ce8a4af16cdc - Slash'EM Extended will use this as long as I can't find the root cause of the problem. Pretty sure there's some xchar or other variable used somewhere but I don't know why...

**Comment by Soviet5lo** [comment] 2015-06-27 21:02
Applied the above fix, it's not a real solution but it's the best anyone can come up with for now until the root of the problem is found and taken care of.

**Comment by Soviet5lo** [comment] 2020-02-03 01:06
This was fixed in commit 2d54ec9 back in 2016 for develop

**Closed by Soviet5lo** 2020-02-03 01:06 UTC
Labels: bug, help wanted
