### ISSUE TITLE
-45 AC naked

### ISSUE THREAD

**Issue by pirate486743186** [Soviet5lo/SlashTHEM#8] opened 2015-06-11 01:38 UTC
I just noticed that i have -45 AC naked. I don't know how this happened.

My status line (clothed)
XXX the Bushou  St18/34 Dx18 Co16 In18 Wi18 Ch18 SamHumFemLaw 
Dlvl:23 $:0  HP:155(236) Pw:128(132) AC:-62 MC:3 Exp:18  T:81946 
I also have 8 AC from protection....
Because of dexterity of 18, it's an other 4 AC bonus (slashem rules)
so it's a -33AC unaccounted for....
i got crowned too, i got a few times "golden grow" from praying
i fond a weapon store with "enchant weapon" and enchanted a bunch of stuff (unicorn, bullets, ....)
i have a +8 excalibur (+1 from crowning)
hand of vecna
3 health stones
free action

Oh well, so mush for ascending without cheating...
I can send my save file if you want.

**Comment by Soviet5lo** [comment] 2015-06-12 01:56
I believe someone else on nxc had a similar issue, but I'm not exactly certain what would cause that.  Hmm...if you can upload the save somewhere, that would be nice.  Latest version released, correct?

**Comment by pirate486743186** [comment] 2015-06-12 02:59
(Unix SlashTHEM Version 0.7.0 - last build May 25 2015 13:51:33)
http://www.4shared.com/file/S-P_A_gIba/1000mike.html

**Comment by Soviet5lo** [comment] 2015-06-13 02:56
Apparently the issue is wearable artifacts that have SPFX_PROTEC do not have their AC bonus calculated correctly upon save/crash and reload, causing the AC to be reduced by 2 during each load.  Seems this also exists in Slash'EM Extended as well, but it's not as common as that variant only has 2 artifacts that grants the tag.

**Comment by AmyBSOD** [comment] 2015-06-17 06:00
Fixed in Slash'EM Extended: https://github.com/SLASHEM-Extended/SLASHEM-Extended/commit/7414294b3d2bb774ef22f2ad7b0c1520807a7da3 - however, the Burned Moth Relay doesn't work at all now even though all the relevant checks should be in place... Artifacts that grant the AC bonus when worn will correctly work without stacking though.

**Comment by pirate486743186** [comment] 2015-06-17 12:23
I can't wish for the "The Burned Moth Relay" in wizard mode, in either variant.

**Comment by AmyBSOD** [comment] 2015-06-18 05:54
Wish for "relay named Burned Moth Relay" instead.

**Comment by Soviet5lo** [comment] 2020-02-03 01:04
Fixed this in 5a90aa3 in develop

**Closed by Soviet5lo** 2020-02-03 01:04 UTC
Labels: bug, help wanted
