### ISSUE TITLE
Can't add multiple items to a sack

### ISSUE THREAD

**Issue by oddhack** [Soviet5lo/SlashTHEM#24] opened 2017-08-27 09:20 UTC
0.8.0 build from commit f5bd49c10a7614075f63a57f3ffb70f6d9d64960

Guessing this project is dead given the commit history, but in case not: I have a sack and a bunch of items in inventory. I apply the sack to put something in, select multiple items from inventory - and only a single one is put into the sack. Likewise with a carried chest - haven't tried with other containers. This is a regression relative to Slash'EM and there aren't any obvious options to control this behavior.

**Comment by moon-chilled** [comment] 2017-08-27 20:34
Yep, it's dead.  Soviet hasn't been on irc for over a year.

**Comment by Soviet5lo** [comment] 2020-02-03 01:07
I'm not exactly sure what commit fixed this one (perhaps de698a4 since I haven't seen this bug since then?) but I can't reproduce it now and haven't been able to since mid 2019.  Fixed in develop.

Apparently the bug only happened if you attempted to drop multiple objects into a container while having any amount of gold.  Strange.

**Closed as completed by Soviet5lo** 2020-02-03 01:07 UTC
